name: Test Docker Build

permissions:
  contents: read
  id-token: write

on:
  pull_request:
    branches:
      - main
      - 'feat/*'
    paths-ignore:
      - docs/**
      - chart/**

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BASE_IMAGE=ghcr.io/obot-platform/obot/base:latest
