name: Update Snapshot Tag

permissions:
  id-token: write
  contents: read
  packages: write

env:
  IMAGE_REPOSITORY: ghcr.io/genesis-ryan-84-0567536339/gen-hub

on:
  workflow_dispatch:
  schedule:
    - cron: "0 21 * * 5"

jobs:
  copy-tag:
    runs-on: ubuntu-22.04

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup crane
        uses: imjasonh/setup-crane@v0.5

      - name: Copy to oss snapshot tag
        run: |
          crane tag "${IMAGE_REPOSITORY}:main" "main-$(date +%Y%m%d)"
